In [1]:
# LABORATORIO 1 - INTELIGENCIA ARTIFICIAL

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Cargar el data set y visualizar los 5 primeros campos

df = pd.read_csv('census.csv')
df.head()

   COUNTY   STNAME         CTYNAME  CENSUS2010POP  BIRTHS2010
0       0  Alabama         Alabama        4779736       14227
1       1  Alabama  Autauga County          54571         151
2       3  Alabama  Baldwin County         182265         516
3       5  Alabama  Barbour County          27457          70
4       7  Alabama     Bibb County          22915          44

In [3]:
#Tamaño de filas y columnas

nfilas = df.shape[0]
ncolum = df.shape[1]
print ('Número de filas: ', nfilas)
print ('Número de columnas: ', ncolum)

Número de filas:  3193
Número de columnas:  5

In [4]:
# Matriz de correlación 

matriz_c = df.corr()
matriz_c

C:\Users\ggarcia\AppData\Local\Temp\ipykernel_5368\920800992.py:3: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  matriz_c = df.corr()

                 COUNTY  CENSUS2010POP  BIRTHS2010
COUNTY         1.000000      -0.089935   -0.086525
CENSUS2010POP -0.089935       1.000000    0.995909
BIRTHS2010    -0.086525       0.995909    1.000000

In [5]:
# Limpiar el dataset (no todos los campos son necesarios, solo use los que necesite)

cleandf=['COUNTY', 'CTYNAME']
df_new=df.drop(cleandf, axis =1)

df_new

       STNAME  CENSUS2010POP  BIRTHS2010
0     Alabama        4779736       14227
1     Alabama          54571         151
2     Alabama         182265         516
3     Alabama          27457          70
4     Alabama          22915          44
...       ...            ...         ...
3188  Wyoming          43806         166
3189  Wyoming          21294          76
3190  Wyoming          21118          72
3191  Wyoming           8533          26
3192  Wyoming           7208          26

[3193 rows x 3 columns]

In [6]:
# Codificar la data categorica

import pandas as pd

cat_dat = pd.get_dummies (df_new['STNAME'], prefix='ST')
df_nect = df_new.drop (['STNAME'], axis=1)
df_nect = pd.concat ([df_nect, cat_dat], axis =1)
df_nect

,CENSUS2010POP,BIRTHS2010,ST_Alabama,ST_Alaska,ST_Arizona,ST_Arkansas,ST_California,ST_Colorado,ST_Connecticut,ST_Delaware,...,ST_South Dakota,ST_Tennessee,ST_Texas,ST_Utah,ST_Vermont,ST_Virginia,ST_Washington,ST_West Virginia,ST_Wisconsin,ST_Wyoming
0,4779736,14227,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,54571,151,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,182265,516,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,27457,70,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,22915,44,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,43806,166,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3189,21294,76,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3190,21118,72,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3191,8533,26,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3192,7208,26,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [7]:
X = df_new [['BIRTHS2010', 'CENSUS2010POP']]
Y = df_new [ 'STNAME']

In [11]:
from sklearn.model_selection import train_test_split

X_entr, X_prue, Y_entr, Y_prue = train_test_split (X, Y, test_size=0.3, stratify=Y)
X_prue

      BIRTHS2010  CENSUS2010POP
1243        2179         743159
229         2547         685306
1774          49          13665
1969          59          24669
1339        1084         330844
...          ...            ...
1936         571         178011
1389          96          32727
843           19          10954
348          157          46389
179           14           8195

[958 rows x 2 columns]

In [12]:

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit (X_prue, Y_prue)

DecisionTreeClassifier()

In [13]:
Y_pred = clf.predict(X_prue)
Y_pred

array(['Massachusetts', 'California', 'Nebraska', 'North Carolina',
       'Minnesota', 'Colorado', 'Kansas', 'Ohio', 'Virginia', 'Indiana',
       'Idaho', 'Ohio', 'North Carolina', 'Pennsylvania', 'Connecticut',
       'Tennessee', 'South Carolina', 'Kansas', 'Texas', 'Wisconsin',
       'Oklahoma', 'Oklahoma', 'Illinois', 'Louisiana', 'Missouri',
       'Arkansas', 'Nebraska', 'Wisconsin', 'Virginia', 'North Dakota',
       'North Carolina', 'Louisiana', 'Alabama', 'Idaho', 'Mississippi',
       'Texas', 'Washington', 'Arkansas', 'Nebraska', 'Arkansas',
       'Michigan', 'Texas', 'Oklahoma', 'Ohio', 'South Dakota', 'Kansas',
       'Louisiana', 'Missouri', 'Oklahoma', 'South Dakota', 'California',
       'Ohio', 'Wisconsin', 'Texas', 'Georgia', 'Alabama', 'Nevada',
       'Indiana', 'Missouri', 'Missouri', 'New Mexico', 'California',
       'New Mexico', 'North Dakota', 'New York', 'New Mexico', 'Indiana',
       'Florida', 'Georgia', 'Missouri', 'Arkansas', 'Texas', 'Wisconsin',
       'Illinois', 'Illinois', 'Louisiana', 'Oregon', 'Iowa', 'Alaska',
       'Indiana', 'Missouri', 'Louisiana', 'California', 'Illinois',
       'Illinois', 'Virginia', 'Oklahoma', 'New York', 'Alabama',
       'Indiana', 'Wisconsin', 'Kentucky', 'Kansas', 'Texas',
       'South Dakota', 'Texas', 'North Dakota', 'Massachusetts', 'Oregon',
       'Virginia', 'Utah', 'Ohio', 'Ohio', 'Alabama', 'Florida', 'Kansas',
       'Louisiana', 'Virginia', 'Indiana', 'South Dakota', 'Minnesota',
       'North Carolina', 'Missouri', 'Texas', 'Tennessee', 'Missouri',
       'Colorado', 'North Dakota', 'Ohio', 'South Dakota', 'Kansas',
       'Pennsylvania', 'Iowa', 'North Dakota', 'Kansas', 'Mississippi',
       'Florida', 'Iowa', 'Maryland', 'Colorado', 'Pennsylvania',
       'Kentucky', 'South Dakota', 'Georgia', 'Rhode Island', 'Texas',
       'Kentucky', 'Tennessee', 'Michigan', 'Idaho', 'Arkansas',
       'Georgia', 'West Virginia', 'Kentucky', 'Kentucky', 'South Dakota',
       'Iowa', 'Vermont', 'Oregon', 'Mississippi', 'Kentucky', 'Nebraska',
       'Illinois', 'North Carolina', 'Florida', 'Wyoming',
       'South Carolina', 'Iowa', 'Montana', 'Georgia', 'Tennessee',
       'South Dakota', 'Oklahoma', 'Georgia', 'Kentucky', 'Mississippi',
       'South Carolina', 'Virginia', 'California', 'Michigan', 'Colorado',
       'Alabama', 'Arkansas', 'Florida', 'South Carolina', 'Ohio',
       'Indiana', 'Colorado', 'Georgia', 'South Carolina', 'Kentucky',
       'Tennessee', 'Nebraska', 'Nebraska', 'Iowa', 'North Carolina',
       'Kansas', 'Tennessee', 'Texas', 'Kentucky', 'Montana', 'Texas',
       'Missouri', 'North Dakota', 'Kentucky', 'Texas', 'Pennsylvania',
       'Indiana', 'Georgia', 'Indiana', 'Illinois', 'Tennessee', 'Texas',
       'Tennessee', 'Arkansas', 'Georgia', 'Wyoming', 'New York',
       'Arkansas', 'California', 'North Carolina', 'Georgia', 'Iowa',
       'Iowa', 'Kansas', 'Oregon', 'Missouri', 'Arkansas', 'Michigan',
       'Alabama', 'Alaska', 'Maryland', 'Mississippi', 'Iowa', 'Illinois',
       'Indiana', 'Montana', 'Florida', 'Texas', 'Kansas', 'Illinois',
       'Kansas', 'Oklahoma', 'South Dakota', 'South Dakota', 'Iowa',
       'Texas', 'Maryland', 'Kansas', 'Missouri', 'Louisiana', 'Kentucky',
       'North Carolina', 'South Dakota', 'Michigan', 'Iowa', 'Maine',
       'Arkansas', 'Kentucky', 'Ohio', 'Wyoming', 'Nebraska', 'Virginia',
       'Kansas', 'Louisiana', 'Kansas', 'Delaware', 'Kansas', 'Indiana',
       'Arkansas', 'Tennessee', 'Nebraska', 'North Carolina', 'Wisconsin',
       'Virginia', 'South Carolina', 'Arkansas', 'Ohio', 'Minnesota',
       'Mississippi', 'Michigan', 'Idaho', 'Indiana', 'Wisconsin',
       'North Carolina', 'Minnesota', 'Michigan', 'Mississippi',
       'Virginia', 'Alabama', 'Michigan', 'Montana', 'Virginia',
       'Florida', 'Kentucky', 'Wisconsin', 'Georgia', 'Kansas',
       'Pennsylvania', 'Ohio', 'New Jersey', 'Texas', 'Mississippi',
       'Kansas', 'Kentucky', 'Iowa', 'South Carolina', 'Minnesota',
       'Missouri', 'Florida', 'Texas', 'Colorado', 'Nebraska', 'Kansas',
       'South Dakota', 'Iowa', 'West Virginia', 'Alabama', 'Washington',
       'Washington', 'Pennsylvania', 'Indiana', 'Mississippi', 'Florida',
       'Maryland', 'Minnesota', 'Utah', 'Oklahoma', 'South Dakota',
       'Indiana', 'Kansas', 'Kentucky', 'Nevada', 'Florida', 'Illinois',
       'Idaho', 'Nebraska', 'Alaska', 'Wisconsin', 'West Virginia',
       'Texas', 'Texas', 'Massachusetts', 'Washington', 'Texas',
       'Alabama', 'Georgia', 'Nebraska', 'Illinois', 'Arkansas',
       'Kentucky', 'Pennsylvania', 'California', 'New Mexico',
       'Mississippi', 'Ohio', 'Mississippi', 'Pennsylvania', 'Vermont',
       'Illinois', 'New York', 'Minnesota', 'Iowa', 'Illinois',
       'Washington', 'Florida', 'Minnesota', 'Georgia', 'Kansas',
       'Kansas', 'Missouri', 'Virginia', 'Texas', 'Michigan', 'Idaho',
       'Oregon', 'Mississippi', 'Idaho', 'Missouri', 'Washington',
       'Texas', 'Georgia', 'Utah', 'North Carolina', 'Montana',
       'Missouri', 'Georgia', 'Virginia', 'Tennessee', 'Oklahoma',
       'Indiana', 'Georgia', 'Illinois', 'Oregon', 'West Virginia',
       'Washington', 'Oklahoma', 'West Virginia', 'Ohio', 'Nebraska',
       'Wisconsin', 'Nebraska', 'Texas', 'Texas', 'Kansas', 'Maryland',
       'Nebraska', 'Kentucky', 'Minnesota', 'Iowa', 'Tennessee', 'Texas',
       'New York', 'Nebraska', 'Indiana', 'California', 'Georgia',
       'Minnesota', 'Texas', 'North Dakota', 'Texas', 'California',
       'Missouri', 'West Virginia', 'Wisconsin', 'California', 'Montana',
       'Missouri', 'Virginia', 'Iowa', 'Minnesota', 'California', 'Texas',
       'Texas', 'North Dakota', 'Iowa', 'South Dakota', 'Virginia',
       'Idaho', 'Virginia', 'Arkansas', 'Indiana', 'Nebraska', 'Georgia',
       'Montana', 'New York', 'Pennsylvania', 'Nebraska', 'Minnesota',
       'Ohio', 'Wyoming', 'Montana', 'Connecticut', 'Indiana', 'Virginia',
       'Texas', 'Florida', 'North Carolina', 'Iowa', 'Mississippi',
       'Wisconsin', 'Georgia', 'Virginia', 'Michigan', 'Tennessee',
       'Wisconsin', 'Washington', 'Minnesota', 'Oklahoma', 'Mississippi',
       'Louisiana', 'Idaho', 'Georgia', 'Georgia', 'Alaska', 'Ohio',
       'South Carolina', 'Virginia', 'Kentucky', 'Kentucky', 'Iowa',
       'Virginia', 'Nebraska', 'Mississippi', 'North Carolina', 'Kansas',
       'Indiana', 'Texas', 'Utah', 'Colorado', 'Oklahoma', 'Tennessee',
       'Mississippi', 'Georgia', 'Iowa', 'Kansas', 'Connecticut',
       'North Dakota', 'Michigan', 'Texas', 'New York', 'Wyoming',
       'Pennsylvania', 'Texas', 'Wisconsin', 'Oregon', 'Nevada',
       'California', 'Tennessee', 'Pennsylvania', 'Georgia', 'Tennessee',
       'Montana', 'Alabama', 'Tennessee', 'South Dakota', 'Alabama',
       'Nebraska', 'Alabama', 'Alaska', 'North Dakota', 'Minnesota',
       'Missouri', 'West Virginia', 'Michigan', 'South Dakota', 'Kansas',
       'Illinois', 'Montana', 'Vermont', 'Nebraska', 'Texas', 'Arkansas',
       'Kansas', 'North Dakota', 'Illinois', 'Illinois', 'Georgia',
       'New Mexico', 'Oregon', 'Georgia', 'Arkansas', 'Georgia', 'Texas',
       'Kansas', 'Virginia', 'Texas', 'Nebraska', 'Montana', 'Alaska',
       'Kansas', 'Illinois', 'Indiana', 'Virginia', 'Nebraska',
       'Pennsylvania', 'Mississippi', 'Louisiana', 'Florida',
       'Massachusetts', 'Georgia', 'North Dakota', 'Kentucky',
       'North Carolina', 'Illinois', 'Missouri', 'Texas', 'Michigan',
       'South Dakota', 'Wisconsin', 'Texas', 'Kentucky', 'North Carolina',
       'Tennessee', 'Colorado', 'Wyoming', 'Oklahoma', 'Virginia',
       'Minnesota', 'Indiana', 'North Dakota', 'North Dakota', 'Texas',
       'Illinois', 'Georgia', 'Minnesota', 'Pennsylvania', 'Alabama',
       'Georgia', 'Kansas', 'Virginia', 'Missouri', 'Colorado',
       'Pennsylvania', 'North Dakota', 'Virginia', 'Missouri',
       'Mississippi', 'Texas', 'Georgia', 'Louisiana', 'South Dakota',
       'Virginia', 'Montana', 'Nebraska', 'Kentucky', 'Nebraska',
       'Illinois', 'Rhode Island', 'Alabama', 'Georgia', 'Alabama',
       'Mississippi', 'Kentucky', 'New York', 'Alaska', 'Minnesota',
       'Louisiana', 'Texas', 'Maine', 'North Carolina', 'Texas',
       'North Carolina', 'Kansas', 'Kentucky', 'Oregon', 'North Carolina',
       'Utah', 'West Virginia', 'Kentucky', 'Louisiana', 'Colorado',
       'Tennessee', 'Pennsylvania', 'New Jersey', 'Virginia', 'Florida',
       'Michigan', 'Maine', 'Hawaii', 'Michigan', 'Texas', 'Missouri',
       'Iowa', 'Florida', 'Missouri', 'Maryland', 'Indiana', 'Missouri',
       'Minnesota', 'Arizona', 'Idaho', 'Texas', 'West Virginia',
       'Georgia', 'Tennessee', 'Pennsylvania', 'Texas', 'Louisiana',
       'Tennessee', 'California', 'Virginia', 'Utah', 'Michigan',
       'New Hampshire', 'Arizona', 'West Virginia', 'Wisconsin',
       'Kentucky', 'Georgia', 'Texas', 'Ohio', 'Ohio', 'Minnesota',
       'Georgia', 'Ohio', 'Oklahoma', 'Indiana', 'Oklahoma', 'New Jersey',
       'Arizona', 'Georgia', 'Montana', 'Minnesota', 'New York',
       'Kentucky', 'Tennessee', 'North Carolina', 'Washington',
       'Oklahoma', 'Louisiana', 'Pennsylvania', 'Hawaii', 'West Virginia',
       'Oklahoma', 'New Jersey', 'Virginia', 'Georgia', 'Maine',
       'Virginia', 'Florida', 'North Carolina', 'Wisconsin',
       'South Carolina', 'Indiana', 'Oklahoma', 'New York', 'Texas',
       'Texas', 'New Mexico', 'Texas', 'Texas', 'Missouri', 'Minnesota',
       'Missouri', 'Washington', 'Tennessee', 'Virginia', 'Texas', 'Ohio',
       'Ohio', 'Iowa', 'Vermont', 'New Mexico', 'Montana', 'Texas',
       'Maryland', 'New York', 'Nevada', 'Oklahoma', 'Colorado',
       'Maryland', 'Illinois', 'Arkansas', 'New Mexico', 'Mississippi',
       'Tennessee', 'Ohio', 'District of Columbia', 'Indiana', 'Colorado',
       'New Jersey', 'Texas', 'Georgia', 'Washington', 'Kentucky',
       'South Carolina', 'Arkansas', 'Colorado', 'Tennessee', 'Missouri',
       'North Carolina', 'California', 'Tennessee', 'Georgia', 'Virginia',
       'Texas', 'Wisconsin', 'Kansas', 'Florida', 'Georgia', 'Virginia',
       'Illinois', 'Kentucky', 'Illinois', 'Oregon', 'New York',
       'Missouri', 'Montana', 'Florida', 'Texas', 'Colorado', 'Virginia',
       'Virginia', 'Colorado', 'Michigan', 'Louisiana', 'Ohio', 'Montana',
       'Alabama', 'Iowa', 'Iowa', 'Illinois', 'Michigan', 'Virginia',
       'New York', 'Iowa', 'West Virginia', 'New York', 'Colorado',
       'West Virginia', 'Iowa', 'Michigan', 'Georgia', 'Georgia',
       'Nevada', 'Missouri', 'Kansas', 'Minnesota', 'Arkansas', 'Alabama',
       'Louisiana', 'Missouri', 'Georgia', 'Colorado', 'Tennessee',
       'Missouri', 'Texas', 'Mississippi', 'Texas', 'New Hampshire',
       'Indiana', 'Missouri', 'South Carolina', 'California', 'Idaho',
       'Oregon', 'Alabama', 'North Carolina', 'North Carolina', 'Texas',
       'Kentucky', 'Kentucky', 'Louisiana', 'Idaho', 'Ohio', 'Texas',
       'New Mexico', 'Texas', 'Pennsylvania', 'Oklahoma', 'Missouri',
       'Minnesota', 'Utah', 'Ohio', 'Wisconsin', 'Ohio', 'Texas',
       'New Hampshire', 'Tennessee', 'Indiana', 'New Jersey', 'Montana',
       'Michigan', 'Illinois', 'New Jersey', 'Idaho', 'Colorado',
       'Michigan', 'Michigan', 'North Carolina', 'Georgia', 'Texas',
       'Wyoming', 'Minnesota', 'Texas', 'Texas', 'Tennessee',
       'North Carolina', 'New York', 'Nebraska', 'Ohio', 'New York',
       'Illinois', 'Iowa', 'Wisconsin', 'Pennsylvania', 'Oklahoma',
       'Kentucky', 'Texas', 'Arkansas', 'New Mexico', 'California',
       'Mississippi', 'Texas', 'Nebraska', 'New York', 'New York',
       'Colorado', 'North Carolina', 'Kentucky', 'Indiana',
       'West Virginia', 'Iowa', 'Georgia', 'West Virginia', 'Kentucky',
       'California', 'Georgia', 'Michigan', 'Idaho', 'North Carolina',
       'South Carolina', 'Maine', 'California', 'Texas', 'Arizona',
       'South Carolina', 'Texas', 'North Dakota', 'Nebraska', 'New York',
       'Oklahoma', 'Alaska', 'Utah', 'Alabama', 'Missouri', 'Louisiana',
       'Texas', 'Mississippi', 'Utah', 'Wisconsin', 'Louisiana',
       'Illinois', 'Pennsylvania', 'Arkansas', 'Virginia', 'Texas',
       'Minnesota', 'Ohio', 'Texas', 'Georgia', 'Virginia',
       'North Carolina', 'Illinois', 'Virginia', 'Oklahoma',
       'South Dakota', 'Texas', 'Colorado', 'Mississippi', 'Virginia',
       'North Carolina', 'Washington', 'Georgia', 'Texas', 'Georgia',
       'Michigan', 'Illinois', 'Iowa', 'Kentucky', 'Tennessee', 'Texas',
       'Texas', 'West Virginia', 'South Dakota', 'Nebraska', 'Kentucky',
       'Alabama', 'Alaska', 'Texas', 'Arizona', 'West Virginia',
       'South Carolina', 'Michigan', 'Wisconsin', 'Mississippi',
       'Virginia', 'Missouri', 'Florida', 'Arkansas', 'Illinois', 'Texas',
       'North Carolina', 'Minnesota', 'Iowa', 'Florida', 'Arkansas'],
      dtype=object)

In [14]:
from sklearn.metrics import accuracy_score, recall_score
accuracy = accuracy_score (Y_prue, Y_pred)
accuracy

1.0

In [15]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix (Y_prue, Y_pred)
cm

array([[20,  0,  0, ...,  0,  0,  0],
       [ 0,  9,  0, ...,  0,  0,  0],
       [ 0,  0,  5, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 17,  0,  0],
       [ 0,  0,  0, ...,  0, 22,  0],
       [ 0,  0,  0, ...,  0,  0,  7]], dtype=int64)

In [20]:
from sklearn.neighbors import KNeighborsClassifier

clk = KNeighborsClassifier()

clk.fit(X_entr, Y_entr)

KNeighborsClassifier()

In [21]:
y_predkn = clk.predict(X_prue)
y_predkn

array(['California', 'Georgia', 'Illinois', 'Indiana', 'Florida',
       'Indiana', 'Virginia', 'Arizona', 'Tennessee', 'Idaho', 'Georgia',
       'Florida', 'Illinois', 'Georgia', 'California', 'Alabama',
       'Mississippi', 'Kansas', 'South Dakota', 'Alabama', 'Michigan',
       'California', 'Kansas', 'Georgia', 'Nebraska', 'Mississippi',
       'Georgia', 'Washington', 'Missouri', 'Kansas', 'California',
       'California', 'Tennessee', 'Illinois', 'Kansas', 'Alabama',
       'Georgia', 'Georgia', 'Idaho', 'Mississippi', 'Iowa', 'Florida',
       'Illinois', 'New York', 'Arkansas', 'South Dakota', 'Missouri',
       'Louisiana', 'Iowa', 'Texas', 'Florida', 'Missouri', 'Illinois',
       'Nebraska', 'Kentucky', 'California', 'California', 'Colorado',
       'Alaska', 'Arkansas', 'Kansas', 'Kentucky', 'Texas', 'Alabama',
       'California', 'Georgia', 'Kentucky', 'Florida', 'Louisiana',
       'Kansas', 'Georgia', 'Kentucky', 'Arkansas', 'Arkansas', 'Texas',
       'Indiana', 'Arizona', 'Kentucky', 'Georgia', 'Michigan',
       'Colorado', 'Washington', 'Colorado', 'Kansas', 'Alabama',
       'California', 'Idaho', 'Kentucky', 'Louisiana', 'Alabama',
       'Illinois', 'Indiana', 'Illinois', 'Kansas', 'Texas', 'Alabama',
       'Colorado', 'Alabama', 'Arkansas', 'Nebraska', 'Florida',
       'North Carolina', 'Delaware', 'Florida', 'Illinois', 'Kansas',
       'Georgia', 'Missouri', 'Florida', 'North Dakota', 'Alabama',
       'Louisiana', 'Michigan', 'New York', 'Texas', 'Wisconsin',
       'Georgia', 'Georgia', 'Alabama', 'North Dakota', 'North Dakota',
       'Georgia', 'Iowa', 'Alaska', 'South Dakota', 'Mississippi',
       'New York', 'Texas', 'Colorado', 'Georgia', 'Illinois', 'Michigan',
       'Arkansas', 'Arkansas', 'Arkansas', 'Colorado', 'Florida',
       'Colorado', 'Kentucky', 'California', 'Alabama', 'Tennessee',
       'Indiana', 'Illinois', 'Georgia', 'Kentucky', 'Texas', 'Illinois',
       'Michigan', 'Virginia', 'California', 'Florida', 'Kansas',
       'Kentucky', 'Indiana', 'Minnesota', 'Arkansas', 'Indiana',
       'North Dakota', 'Wisconsin', 'Maryland', 'Idaho', 'Alabama',
       'Arkansas', 'Colorado', 'Florida', 'Arkansas', 'Florida', 'Alaska',
       'Missouri', 'Illinois', 'Colorado', 'Georgia', 'Mississippi',
       'Michigan', 'Alabama', 'Georgia', 'Montana', 'Michigan',
       'California', 'Missouri', 'Georgia', 'West Virginia', 'Kansas',
       'Colorado', 'Illinois', 'Idaho', 'Alabama', 'Louisiana', 'Georgia',
       'Texas', 'Illinois', 'Arkansas', 'California', 'West Virginia',
       'Virginia', 'Georgia', 'Idaho', 'Georgia', 'Georgia', 'Minnesota',
       'Kansas', 'Alabama', 'Alabama', 'Indiana', 'California',
       'North Dakota', 'Louisiana', 'Iowa', 'California', 'Alabama',
       'Kentucky', 'Georgia', 'Alabama', 'Indiana', 'Indiana',
       'California', 'Kentucky', 'Colorado', 'Massachusetts', 'Oregon',
       'Alabama', 'California', 'Colorado', 'Illinois', 'Virginia',
       'Kentucky', 'Hawaii', 'Florida', 'California', 'Arizona', 'Texas',
       'Arkansas', 'Minnesota', 'Kansas', 'Georgia', 'Georgia', 'Florida',
       'Texas', 'Maryland', 'Georgia', 'Iowa', 'California', 'Kansas',
       'Georgia', 'Illinois', 'Kansas', 'Georgia', 'New York', 'Alabama',
       'Alaska', 'Georgia', 'California', 'Georgia', 'Arkansas',
       'Alabama', 'Ohio', 'Alaska', 'Arkansas', 'Arkansas', 'Mississippi',
       'Massachusetts', 'Georgia', 'Louisiana', 'North Carolina',
       'Georgia', 'Georgia', 'Indiana', 'Florida', 'Kentucky', 'Florida',
       'Georgia', 'Idaho', 'Michigan', 'Alabama', 'North Dakota',
       'Mississippi', 'Illinois', 'Alabama', 'Alabama', 'Georgia',
       'Arkansas', 'Georgia', 'Indiana', 'Arkansas', 'Iowa', 'California',
       'Georgia', 'Indiana', 'North Carolina', 'Illinois', 'Colorado',
       'Louisiana', 'Ohio', 'Kansas', 'Indiana', 'Connecticut', 'Iowa',
       'Missouri', 'Connecticut', 'Idaho', 'Maryland', 'Colorado',
       'Texas', 'Louisiana', 'Alabama', 'Alabama', 'Iowa', 'California',
       'California', 'Arkansas', 'Texas', 'Florida', 'Kentucky',
       'Michigan', 'Idaho', 'Iowa', 'Washington', 'Iowa', 'Maryland',
       'Indiana', 'Georgia', 'Alabama', 'Idaho', 'South Dakota',
       'Georgia', 'Nebraska', 'Nebraska', 'Maryland', 'Georgia', 'Texas',
       'Oklahoma', 'Texas', 'Georgia', 'Kansas', 'Idaho', 'Arizona',
       'Georgia', 'Colorado', 'Minnesota', 'Florida', 'Illinois',
       'Georgia', 'Alabama', 'Hawaii', 'Alabama', 'Alabama', 'California',
       'Ohio', 'Colorado', 'North Carolina', 'Michigan', 'Alabama',
       'Michigan', 'Alaska', 'Arkansas', 'Illinois', 'Illinois', 'Kansas',
       'Alaska', 'Louisiana', 'Missouri', 'Alaska', 'Georgia', 'Idaho',
       'Michigan', 'Oklahoma', 'Arkansas', 'Oregon', 'Tennessee', 'Texas',
       'Oregon', 'Virginia', 'Illinois', 'Georgia', 'Kansas', 'Arkansas',
       'Texas', 'Georgia', 'Mississippi', 'Florida', 'Kansas', 'Illinois',
       'Alabama', 'Alabama', 'Colorado', 'Iowa', 'Iowa', 'Florida',
       'Idaho', 'Florida', 'Indiana', 'Georgia', 'Arkansas', 'Colorado',
       'California', 'Alabama', 'California', 'Indiana', 'Missouri',
       'Michigan', 'Arkansas', 'Alabama', 'Colorado', 'Oklahoma',
       'Washington', 'Florida', 'Maryland', 'Virginia', 'Indiana',
       'Missouri', 'Florida', 'Nebraska', 'Florida', 'Alabama',
       'South Carolina', 'Montana', 'Kansas', 'Arkansas', 'Kentucky',
       'Arkansas', 'California', 'Montana', 'Idaho', 'Alabama',
       'Kentucky', 'Nebraska', 'Wyoming', 'Kansas', 'Alabama', 'Alabama',
       'Tennessee', 'Florida', 'Texas', 'Idaho', 'Alaska', 'Iowa', 'Iowa',
       'Illinois', 'Georgia', 'Alabama', 'Colorado', 'Connecticut',
       'Alabama', 'Georgia', 'Missouri', 'Washington', 'Missouri',
       'Kentucky', 'Alabama', 'California', 'Florida', 'Kentucky',
       'California', 'Colorado', 'Alabama', 'North Carolina', 'Arkansas',
       'Nebraska', 'Georgia', 'Colorado', 'Colorado', 'Tennessee',
       'Nebraska', 'North Dakota', 'California', 'Virginia', 'Georgia',
       'Tennessee', 'Illinois', 'Kentucky', 'Arkansas', 'Nebraska',
       'Colorado', 'Georgia', 'Missouri', 'Alabama', 'Florida',
       'California', 'Georgia', 'Georgia', 'Arkansas', 'South Carolina',
       'Georgia', 'Arkansas', 'Massachusetts', 'Iowa', 'Georgia', 'Ohio',
       'South Dakota', 'Alabama', 'South Carolina', 'Alaska', 'Georgia',
       'Alabama', 'Georgia', 'Alaska', 'Illinois', 'Indiana', 'Illinois',
       'Alabama', 'Alabama', 'Iowa', 'Colorado', 'Indiana', 'Illinois',
       'Idaho', 'Alaska', 'Michigan', 'Texas', 'Mississippi', 'Oklahoma',
       'Illinois', 'Virginia', 'Alaska', 'Colorado', 'Indiana', 'Alabama',
       'Texas', 'Kentucky', 'North Dakota', 'Arkansas', 'California',
       'Ohio', 'Iowa', 'Colorado', 'California', 'Ohio', 'Texas',
       'Georgia', 'California', 'Arkansas', 'Iowa', 'Indiana',
       'North Dakota', 'Kentucky', 'Alabama', 'Georgia', 'Arkansas',
       'Kansas', 'Alaska', 'Georgia', 'Alabama', 'Iowa', 'Oregon',
       'Arkansas', 'Alabama', 'Virginia', 'Arkansas', 'New York',
       'Georgia', 'Colorado', 'Florida', 'Illinois', 'Virginia', 'Kansas',
       'Texas', 'West Virginia', 'Nebraska', 'Illinois', 'Minnesota',
       'Louisiana', 'Illinois', 'Florida', 'Arkansas', 'Colorado',
       'Florida', 'Florida', 'Illinois', 'Ohio', 'Colorado', 'Georgia',
       'Texas', 'Georgia', 'Kansas', 'Tennessee', 'New Mexico', 'Alabama',
       'Arkansas', 'Missouri', 'Missouri', 'Indiana', 'Illinois', 'Ohio',
       'Montana', 'Idaho', 'Arizona', 'Alabama', 'Georgia', 'Oklahoma',
       'Georgia', 'North Dakota', 'Georgia', 'Alaska', 'Kansas',
       'Louisiana', 'Arkansas', 'Indiana', 'Colorado', 'Georgia',
       'Arkansas', 'Illinois', 'Missouri', 'Alabama', 'Florida',
       'Virginia', 'Louisiana', 'Arkansas', 'Texas', 'Alabama',
       'California', 'Louisiana', 'West Virginia', 'Arkansas',
       'Tennessee', 'Kentucky', 'Tennessee', 'Tennessee', 'Arkansas',
       'Mississippi', 'Iowa', 'Georgia', 'Indiana', 'California',
       'Colorado', 'Georgia', 'Washington', 'Oklahoma', 'Illinois',
       'Arizona', 'North Dakota', 'Colorado', 'Colorado', 'Indiana',
       'Colorado', 'Iowa', 'Colorado', 'Kentucky', 'Arkansas', 'Georgia',
       'Maryland', 'Kansas', 'Iowa', 'Indiana', 'Montana', 'Illinois',
       'Louisiana', 'Tennessee', 'North Carolina', 'Illinois', 'New York',
       'Montana', 'Alabama', 'Tennessee', 'Alaska', 'Alabama', 'Arkansas',
       'Alabama', 'Florida', 'Tennessee', 'Virginia', 'Arkansas',
       'Arkansas', 'Colorado', 'Indiana', 'Arizona', 'Texas', 'Iowa',
       'Alabama', 'California', 'California', 'Missouri', 'Alabama',
       'Alaska', 'California', 'Illinois', 'Idaho', 'Georgia', 'New York',
       'Tennessee', 'Michigan', 'Illinois', 'Illinois', 'Arkansas',
       'Kansas', 'Indiana', 'Kentucky', 'Georgia', 'Louisiana',
       'Illinois', 'Connecticut', 'Missouri', 'California', 'Minnesota',
       'Indiana', 'Texas', 'Idaho', 'Texas', 'Colorado', 'Arkansas',
       'Alaska', 'Kansas', 'Kentucky', 'Louisiana', 'Connecticut',
       'Illinois', 'Minnesota', 'Georgia', 'Tennessee', 'Arkansas',
       'Iowa', 'Texas', 'Kansas', 'Georgia', 'Georgia', 'North Carolina',
       'California', 'Missouri', 'California', 'Idaho', 'Massachusetts',
       'California', 'California', 'North Carolina', 'Mississippi',
       'Virginia', 'Indiana', 'Indiana', 'Colorado', 'Florida',
       'Missouri', 'Connecticut', 'Florida', 'Iowa', 'California',
       'Tennessee', 'Georgia', 'Alabama', 'Iowa', 'Minnesota', 'Kansas',
       'Iowa', 'Kentucky', 'Alabama', 'Hawaii', 'Arkansas', 'Arkansas',
       'Maryland', 'Idaho', 'California', 'Arkansas', 'Georgia',
       'Arkansas', 'Texas', 'Georgia', 'Michigan', 'Arkansas', 'Kentucky',
       'Georgia', 'California', 'Alabama', 'South Dakota', 'Georgia',
       'Arkansas', 'Kansas', 'Georgia', 'Missouri', 'Indiana', 'Kansas',
       'Florida', 'Missouri', 'Kentucky', 'Alabama', 'Arkansas',
       'Virginia', 'Florida', 'Illinois', 'Alabama', 'California',
       'Kentucky', 'Alaska', 'Indiana', 'Arkansas', 'Florida', 'Iowa',
       'Illinois', 'Georgia', 'Nebraska', 'Kansas', 'Texas', 'Indiana',
       'Iowa', 'Alaska', 'Texas', 'Louisiana', 'Arkansas', 'Illinois',
       'California', 'Virginia', 'Georgia', 'Alabama', 'Minnesota',
       'Alabama', 'California', 'Kansas', 'Arkansas', 'Idaho', 'Alabama',
       'Tennessee', 'Connecticut', 'Kansas', 'Michigan', 'Georgia',
       'Colorado', 'Florida', 'Indiana', 'Nebraska', 'Kansas', 'Georgia',
       'Florida', 'Ohio', 'Oklahoma', 'Kentucky', 'Michigan', 'Florida',
       'Indiana', 'Arkansas', 'Pennsylvania', 'Colorado', 'Virginia',
       'Iowa', 'Colorado', 'Virginia', 'Alabama', 'Colorado', 'Georgia',
       'Iowa', 'Colorado', 'Indiana', 'Florida', 'Tennessee', 'Kansas',
       'Kansas', 'Minnesota', 'Georgia', 'Georgia', 'Alaska', 'Arkansas',
       'Arkansas', 'Kentucky', 'Georgia', 'North Carolina', 'Ohio',
       'Alabama', 'Georgia', 'Arizona', 'Kentucky', 'South Dakota',
       'Indiana', 'Idaho', 'Georgia', 'Alabama', 'Florida', 'Oregon',
       'Alabama', 'Alaska', 'Maryland', 'Indiana', 'California', 'Texas',
       'Wyoming', 'California', 'Ohio', 'Arkansas', 'Arkansas', 'Georgia',
       'Michigan', 'Washington', 'Kentucky', 'Kentucky', 'Idaho',
       'Kentucky', 'Arkansas', 'Tennessee', 'Ohio', 'Indiana', 'Kentucky',
       'Alaska', 'Kentucky', 'Minnesota', 'California', 'Colorado',
       'Alabama', 'Arkansas', 'Georgia', 'Florida', 'Louisiana',
       'Kentucky', 'Missouri', 'Virginia', 'Kansas', 'Alaska', 'Arkansas',
       'Georgia', 'Ohio', 'Indiana', 'Arkansas', 'Kansas', 'Georgia',
       'Texas', 'Illinois', 'Illinois', 'Alabama', 'California',
       'Georgia', 'Michigan', 'Virginia', 'Colorado', 'North Dakota',
       'Georgia', 'Idaho', 'Arkansas', 'California', 'Alabama', 'Texas',
       'Kansas', 'North Carolina', 'Arkansas', 'Illinois', 'Georgia',
       'Illinois', 'California', 'Texas', 'Arkansas', 'Maryland',
       'North Dakota', 'Colorado', 'Indiana', 'Alabama', 'Alaska',
       'Texas', 'Alabama', 'Missouri', 'Florida', 'Alabama', 'Texas',
       'Georgia', 'Michigan', 'Kentucky', 'Kentucky', 'Alabama',
       'Alabama', 'New York', 'California', 'Michigan', 'Idaho',
       'Arkansas', 'Arkansas'], dtype=object)

In [22]:
accuracykn = accuracy_score(Y_prue, y_predkn)
accuracykn

0.04279749478079332